### ISSUE TITLE
Alternative to manual DOT installation with anaconda

### ISSUE THREAD

**Issue by ddceruti** [ricnogfer/pypsatopo#15]
Hi, 
I am using pypsatopo for pypsa network visualization and I love the package. I found a quicker way to make it run with anaconda (or mamba) by installing `python-graphviz` [https://anaconda.org/conda-forge/python-graphviz](https://anaconda.org/conda-forge/python-graphviz) from conda-forge. The dependency may be a bit bloated, but it works well for the latest pip version of pypsatopo and is not mentioned in [https://graphviz.org/download/](https://graphviz.org/download/).
Hope someone finds this useful!

**Comment by ricnogfer** [comment]
Hi @ddceruti,

Thanks for the feedback - PyPSATopo documentation will soon be updated to take into account your useful finding.

**Comment by ricnogfer** [comment]
This issue is solved with commit c3f82adca37cb095833290a3e6a5e47d37c849cb.
