### ISSUE TITLE
Add capability to represent graphically pypsa Storage Unit component.

### ISSUE THREAD

**Issue by SleimanFarah** [ricnogfer/pypsatopo#17]

**Comment by ricnogfer** [comment]
Thanks to the latest commit (https://github.com/ricnogfer/pypsatopo/commit/94954d733d38b2fc477ae5c5b9a4f28ceeb6bf1c), PyPSATopo can now graphically represent storage units. Please feel free to test it and post here if you encounter an issue related to this, @SleimanFarah.

**Comment by ricnogfer** [comment]
Closing the issue as it has been solved/implemented.
